VEN-668 | Sending multiple offers
City-of-Helsinki/berth-reservations-admin pull request #313
Opened 2020-10-27 08:12 UTC by Nizar-Rahme

## Description :sparkles:

## Issues :bug:

### Closes :no_good_woman:
[**VEN-668:**](https://helsinkisolutionoffice.atlassian.net/browse/VEN-668) Add a dialog for sending offers

### Related :handshake:

## Testing :alembic:

### Automated tests :gear:️

### Manual testing :construction_worker_man:
- Go to berth applications list view
- Select multiple applications
- "Lähteä tarjous" button at the top will be activated, click it to open a model 
- Set the due date and send the offers

Note: Selecting unhandled offers would display an error message to warn the admin.

## Screenshots :camera_flash:
![image](https://user-images.githubusercontent.com/23040926/97273850-85649d00-183c-11eb-94a9-7cffb2b1fdbb.png)
![image](https://user-images.githubusercontent.com/23040926/97274183-f3a95f80-183c-11eb-9b3a-2c44b2791781.png)

## Additional notes :spiral_notepad:

2020-10-27 13:25 UTC, TatuArvela requested changes
A couple of things to correct, but otherwise it's looking good. Very nicely done! 👍

2020-10-27 13:25 UTC, TatuArvela commented on src/features/applicationList/ApplicationList.tsx
> +            });
Worked nicely, but I couldn't read it in time 😄 Maybe disable auto-dismiss for this one, with the prop `autoDismiss: false`

2020-10-27 13:25 UTC, TatuArvela commented on src/locales/fi.json
> +      "title": "Lähetä Tarjous",
Minor typo, should be "Lähetä tarjous"

2020-10-27 13:25 UTC, TatuArvela commented on src/locales/fi.json
> +      "sendOffer": "Lähteä tarjous",
Typo, should be "Lähetä tarjous"

2020-11-02 15:04 UTC, TatuArvela commented
I rebased this, but I definitely need another set of eyes to look at this. @ahie or @santtul ?

2020-11-03 08:54 UTC, ahie reviewed
Left a couple comments, otherwise LGTM.

2020-11-03 08:54 UTC, ahie commented on src/features/applicationList/ApplicationListContainer.tsx
> +    } catch (error) {}
Should an error toast be shown here?

2020-11-03 08:54 UTC, ahie commented on src/features/unmarkedWsNoticeList/UnmarkedWsNoticeList.tsx
> +          const offers = getDraftedOffers(selectedRows);
Should this logic be in `ApplicationListTools` instead? Now it's still possible to send the BE request even though `offers` contains ones without places?

2020-11-03 08:54 UTC, ahie commented on src/features/applicationListTools/ApplicationListTools.tsx
> +  handleApproveOrders(): Promise<void>;
Optional: Not sure about the `Promise<void>` return type here, as we usually just pass synchronous functions to components. Could refactor?

2020-11-03 08:54 UTC, ahie commented on src/features/applicationList/ApplicationList.tsx
> +          const offers = getDraftedOffers(selectedRows);
Same comment here as in unmarked ws notice list: the additional logic could be moved to the `ApplicationListTools` component?

2020-11-03 08:57 UTC, ahie commented on src/features/applicationList/ApplicationListContainer.tsx
> +    } catch (error) {}
Typically these handlers are synchronous and the success toast is triggered in a `then` block, while the error is handled by the generic error handler.

2020-11-04 10:59 UTC, TatuArvela approved these changes

2020-11-04 11:04 UTC, TatuArvela commented
Rebased to `develop`. Had to rewrite the commits a bit to make this cleaner. Some changes were on the wrong commits when compared to commit titles, and did not pass tests or type checks.

2020-11-05 10:56 UTC, ahie approved these changes
LGTM 👍

2020-11-05 11:28 UTC, merged