VEN-1027 | Disable 'edit additional services' button if invoice is sent
City-of-Helsinki/berth-reservations-admin pull request #346
Opened 2020-12-04 12:50 UTC by TatuArvela

## Description :sparkles:

* Disable 'edit additional services' button if invoice is sent

## Issues :bug:

### Closes :no_good_woman:

* [VEN-1027](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1027): Invoice 'edit additional services' button should be inactive if invoice is sent

## Testing :alembic:

### Automated tests :gear:️

### Manual testing :construction_worker_man:

2020-12-07 07:54 UTC, santtul requested changes
Seems to work, but should we indicate that the button is disabled in the UI somehow (e.g. by graying it) for better usability?

2020-12-07 11:12 UTC, TatuArvela commented
> Seems to work, but should we indicate that the button is disabled in the UI somehow (e.g. by graying it) for better usability?

I replaced the button with an actual small button, which is grayed when it is disabled

2020-12-10 08:47 UTC, Nizar-Rahme approved these changes
LGTM!

2020-12-10 15:31 UTC, ahie approved these changes
LGTM 👍

2020-12-16 11:29 UTC, merged